# C++ Build Template
name: C++ CI/CD

on:
  workflow_dispatch:
  
jobs:
  build:
  - name: Install build tools
    run: sudo apt-get update && sudo apt-get install -y build-essential

  - name: Compile C++ code
    run: |
      mkdir -p build
      g++ -o build/app *.cpp
      echo "C++ build complete"
