# Java Build Template
name: Java CI/CD

on:
  workflow_dispatch:
   paths:
    - '**/generated_java_docker.yml'
   tags:
    - 'v*.*.*'  # semantic version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

