# Python Build Template
name: Python CI/CD

on:
  workflow_dispatch:
  
jobs:
   build:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Build
      run: |
        echo "Python project build complete"
