name: Generate GitHub Workflow

on:
  push:
    branches: 
      - main
      - dev
      - staging
    paths:
      - '**/*.java'
      - '**/*.py'
      - '**/*.cpp'
      - '**/*.cxx'
      - '**/Dockerfile'
      - '.ci/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate git diff
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Fetch origin/main
        run: git fetch origin main

      - name: Generate workflow
        run: python .ci/generate_workflow.py

      - name: Commit generated workflow
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/generated*.yml
          git commit -m "Auto-generate GitHub Actions workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GEN }}@github.com/${{ github.repository }}.git HEAD:main
