name: Terraform Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - dev
      - staging
      - main
    tags:
      - 'v*.*.*'  # semantic version tags like v1.0.0
  pull_request:
    branches:
      - dev
      - staging
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
